### ISSUE TITLE
POI Design Constraints

### ISSUE THREAD

**Issue by craig95** [craig95/Team-C-Sharp#16]
Update POI Design Constraints

**Comment by Seonin** [comment]
Getting the current location will be difficult using WiFi because it is hard to triangulate the position of one device due to the face that the WiFi signal will not give you an accurate representation of where the device is. At best the current location might vary by 10m to 15m depending on the objects it had to pass though e.g. wall or roof. If the user cannot get WiFi signal it will be hard for the user to get the current location because then it will be using the users data and the user might be reluctant to allow that.

**Comment by craig95** [comment]
Updated POI  Design Constraints
